# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Video.create(title: "Futurama", small_cover_url: "/tmp/futurama.jpg", large_cover_url: "/tmp/futurama_large.jpg", description: "Pizza boy Philip J. Fry awakens in the 31st century after 1,000 years of cryogenic preservation in this animated series. After he gets a job at an interplanetary delivery service, Fry embarks on ridiculous escapades to make sense of his predicament.", category_id: 1)
Video.create(title: "South Park", small_cover_url: "/tmp/south_park.jpg", large_cover_url: "/tmp/south_park_large.jpg", description: "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.", category_id: 1)
Video.create(title: "Family Guy", small_cover_url: "/tmp/family_guy.jpg", large_cover_url: "/tmp/family_guy_large.jpg", description: "The Griffin household includes two teenagers, a cynical dog who is smarter than everyone else, and an evil baby who makes numerous attempts to eradicate his mother. Heading up this eclectic household is Peter Griffin. Peter does his best to do what's right for the family, but along the way, he makes mistakes that are the stuff of legends.", category_id: 1)
Video.create(title: "Ghostbusters", small_cover_url: "/tmp/ghostbusters_small.jpg", large_cover_url: "/tmp/ghostbusters_large.jpg", description: "Three odd-ball scientists get kicked out of their cushy positions at a university in New York City where they studied the occult. They decide to set up shop in an old firehouse and become Ghostbusters, trapping pesky ghosts, spirits, haunts, and poltergeists for money. They wise-crack their way through the city, and stumble upon a gateway to another dimension, one which will release untold evil upon the city. The Ghostbusters are called on to save the Big Apple.", category_id: 2)
Video.create(title: "Touching the Void", small_cover_url: "/tmp/touchingTheVoid_small.jpg", large_cover_url: "/tmp/touchingTheVoid_large.jpg", description: "In the mid-80's two young climbers attempted to reach the summit of Siula Grande in Peru; a feat that had previously been attempted but never achieved. With an extra man looking after base camp, Simon and Joe set off to scale the mount in one long push over several days. The peak is reached, however on the descent Joe falls and breaks his leg. Despite what it means, the two continue with Simon letting Joe out on a rope for 300 meters, then descending to join him and so on. However when Joe goes out over an overhang with no way of climbing back up, Simon makes the decision to cut the rope. Joe falls into a crevasse and Simon, assuming him dead, continues back down. Joe however survives the fall and was lucky to hit a ledge in the crevasse. This is the story of how he got back down.", category_id: 3)
Video.create(title: "Futurama", small_cover_url: "/tmp/futurama.jpg", large_cover_url: "/tmp/futurama_large.jpg", description: "Pizza boy Philip J. Fry awakens in the 31st century after 1,000 years of cryogenic preservation in this animated series. After he gets a job at an interplanetary delivery service, Fry embarks on ridiculous escapades to make sense of his predicament.", category_id: 1)
Video.create(title: "South Park", small_cover_url: "/tmp/south_park.jpg", large_cover_url: "/tmp/south_park_large.jpg", description: "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.", category_id: 1)
Video.create(title: "Family Guy", small_cover_url: "/tmp/family_guy.jpg", large_cover_url: "/tmp/family_guy_large.jpg", description: "The Griffin household includes two teenagers, a cynical dog who is smarter than everyone else, and an evil baby who makes numerous attempts to eradicate his mother. Heading up this eclectic household is Peter Griffin. Peter does his best to do what's right for the family, but along the way, he makes mistakes that are the stuff of legends.", category_id: 1)
Video.create(title: "Ghostbusters", small_cover_url: "/tmp/ghostbusters_small.jpg", large_cover_url: "/tmp/ghostbusters_large.jpg", description: "Three odd-ball scientists get kicked out of their cushy positions at a university in New York City where they studied the occult. They decide to set up shop in an old firehouse and become Ghostbusters, trapping pesky ghosts, spirits, haunts, and poltergeists for money. They wise-crack their way through the city, and stumble upon a gateway to another dimension, one which will release untold evil upon the city. The Ghostbusters are called on to save the Big Apple.", category_id: 2)
Video.create(title: "Touching the Void", small_cover_url: "/tmp/touchingTheVoid_small.jpg", large_cover_url: "/tmp/touchingTheVoid_large.jpg", description: "In the mid-80's two young climbers attempted to reach the summit of Siula Grande in Peru; a feat that had previously been attempted but never achieved. With an extra man looking after base camp, Simon and Joe set off to scale the mount in one long push over several days. The peak is reached, however on the descent Joe falls and breaks his leg. Despite what it means, the two continue with Simon letting Joe out on a rope for 300 meters, then descending to join him and so on. However when Joe goes out over an overhang with no way of climbing back up, Simon makes the decision to cut the rope. Joe falls into a crevasse and Simon, assuming him dead, continues back down. Joe however survives the fall and was lucky to hit a ledge in the crevasse. This is the story of how he got back down.", category_id: 3)
futurama = Video.create(title: "Futurama", small_cover_url: "/tmp/futurama.jpg", large_cover_url: "/tmp/futurama_large.jpg", description: "Pizza boy Philip J. Fry awakens in the 31st century after 1,000 years of cryogenic preservation in this animated series. After he gets a job at an interplanetary delivery service, Fry embarks on ridiculous escapades to make sense of his predicament.", category_id: 1)

Category.create(name: "TV Comedy")
Category.create(name: "Comedy")
Category.create(name: "Documentary")

dave = User.create(email: "dave@example.com", password: "test", full_name: "Dave F")

Review.create(user: dave, video: futurama, rating: 5, content: "This is a really great movie!")
Review.create(user: dave, video: futurama, rating: 2, content: "This is a really horrible movie!")